### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [flor-master/kottans-homework#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by flor-master** [comment]
https://github.com/flor-master/kottans-homework/commit/0017cd9bc18c41b92d615bb5c06fba7d84b221fe

**Comment by sudodoki** [comment]
LGMT
